FROM maven:3.8.4-openjdk-11 AS build
WORKDIR /app

COPY . /app/

CMD ["/bin/bash"]

# create a new spring boot project
# CMD ["mvn", "archetype:generate", "-DgroupId=leetcode-algorithm", "-DartifactId=first-leetcode-algorithm", "-Dversion=1.0.0-SNAPSHOT", "-DinteractiveMode=false", "-Dpackage=leetcode.algorithm"]

